name: cppcheck_Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: Windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: analyse
      run: cppcheck --enable=all 3_Implementation
